### ISSUE TITLE
Abilities sometimes do not update when changing shop tabs 

### ISSUE THREAD

**Issue by thespbgamer** [LeonarthCG/FFTA_Engine_Hacks#1]
**Error description:** In the shop when you have the info enabled in the shield menu and you change to the accessories tab the abilities do not update.
**Options I picked**: Default Options + stealShoes
**ROM Used:** Clean USA ROM

**Bug:**
![Error](https://user-images.githubusercontent.com/30112696/78361274-0a8e1900-75b0-11ea-9b7b-847f5c82c48f.png)

**Comment by LeonarthCG** [comment]
This issue has been now solved: https://github.com/LeonarthCG/FFTA_Engine_Hacks/commit/24d45b1c34964fd44fa1674bdcb8155a114cb22f

Sorry for taking this long to get to something so easy to fix...
